import React from "react";
import * as Icon from "react-feather";
const navigationConfig = [
  {
    id: "dashboard",
    title: "DASHBOARD",
    type: "item",
    permissions: ["admin", "editor"],
    navLink: "/",
  },
  {
    type: "groupHeader",
    groupTitle: "User register list",
  },
  {
    id: "registerUserList",
    title: "User list ",
    type: "item",
    icon: <Icon.ArrowRight size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/app/brahmaand/registeruser/registerUserList",
  },
  {
    type: "groupHeader",
    groupTitle: "Category",
  },
  {
    id: "addCategory",
    title: "List of category ",
    type: "item",
    icon: <Icon.ArrowRight size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/app/brahmaand/category/categoryList",
  },
  {
    type: "groupHeader",
    groupTitle: "Subcategory",
  },
  {
    id: "addSubcategory",
    title: " List of subcategory",
    type: "item",
    icon: <Icon.ArrowRight size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/app/brahmaand/subcategory/subcategoryList",
  },
  // {
  //   id: "membershipList",
  //   title: "Membership List",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/membership/membershipList",
  // },
  // {
  //   id: "packagePlanList",
  //   title: "Active Members ",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/package/packagePlanList",
  // },

  {
    type: "groupHeader",
    groupTitle: "Resources list ",
  },
  {
    id: " Admin ResourceList",
    title: "List of Promoted resource ",
    type: "item",
    icon: <Icon.ArrowRight size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/app/brahmaand/resource/resourceList",
  },
  {
    id: "User ResourceList",
    title: "List of User resource   ",
    type: "item",
    icon: <Icon.ArrowRight size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/app/brahmaand/resource/userResourceList",
  },
  {
    id: "ResourceComment",
    title: "List of Resource Comment  ",
    type: "item",
    icon: <Icon.ArrowRight size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/app/brahmaand/resource/resourceComment",
  },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Add sponsor ",
  // },

  // {
  //   id: "basedCategory",
  //   title: "Based on category list  ",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/brahmaand/sponsor/basedCategory",
  // },
  // {
  //   id: "basedSubCategory",
  //   title: "based on subcategory list ",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   // navLink: "/app/package/nonActivePlanList",
  //   navLink: "/app/brahmaand/sponsor/basedSubCategory",
  // },
  {
    type: "groupHeader",
    groupTitle: "Blog",
  },
  {
    id: "blogs",
    title: "Blog List",
    type: "item",
    icon: <Icon.ArrowRight size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/app/brahmaand/blogs/blogList",
  },
  {
    id: "blogs",
    title: "Comment Blog",
    type: "item",
    icon: <Icon.ArrowRight size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/app/brahmaand/blogs/commentBlog",
  },
  {
    type: "groupHeader",
    groupTitle: "LeaderBoard",
  },
  {
    id: "leaderBoard",
    title: "leaderboard leaders ",
    type: "item",
    icon: <Icon.ArrowRight size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/app/brahmaand/leaderboard/leaderBoardList",
  },
  {
    id: "leaderBoard",
    title: "Weekly Winner ",
    type: "item",
    icon: <Icon.ArrowRight size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/app/brahmaand/leaderboard/weeklyWinner",
  },
  {
    id: "feature Content",
    title: "Feature Content ",
    type: "item",
    icon: <Icon.ArrowRight size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/app/brahmaand/content/featureContent",
  },
  {
    id: "notification",
    title: "Notification ",
    type: "item",
    icon: <Icon.ArrowRight size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/app/notif/notification",
  },
  {
    id: "contact",
    title: "Contact ",
    type: "item",
    icon: <Icon.ArrowRight size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/app/brahmaand/contact/Contact",
  },
  {
    id: "newsLetter",
    title: "NewsLetter ",
    type: "item",
    icon: <Icon.ArrowRight size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/app/brahmaand/newsletter/NewsLetter",
  },
  {
    id: "logout",
    title: "Logout",
    type: "item",
    icon: <Icon.ArrowRight size={12} />,
    permissions: ["admin", "editor"],
    // navLink: "/pages/login",
  },



  // {
  //   id: "nonActivePlanList",
  //   title: "Transction History ",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   // navLink: "/app/package/nonActivePlanList",
  //   navLink: "/",
  // },
  // {
  //   id: "feedbackList",
  //   title: "Feedback List ",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/feedback/feedbackList",
  // },
  // {
  //   id: "userAppreciation",
  //   title: "User Appreciation List ",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/showAppre/userAppreciation",
  // },

  // {
  //   id: "login",
  //   title: "Logout ",
  //   type: "item",
  //   permissions: ["admin", "editor"],
  //   navLink: "/pages/login",
  // },
];
export default navigationConfig;
